## Numerical Python

#### VECTOR
- A vector is an array with a single dimension (there is no difference b/w row and column vector.
#### MATRIX
- A matrix refer to an array wtih two dimensions.

#### 1-D Array

In [4]:
import numpy as np
arr = np.array([3,7,10])
arr

array([ 3,  7, 10])

---

In [9]:
# Type of Array
type(arr)

numpy.ndarray

---

In [6]:
# Length of array
len(arr)

3

---

In [16]:
# Element from 0th index
arr[0]

3

---

In [17]:
# All Elements from start to end using indexing
arr[0:]

array([ 3,  7, 10])

---

1). Array with all elements are zeroes.

In [18]:
zero_arr = np.zeros(3)
zero_arr

array([0., 0., 0.])

---

2). Array with all elements are One.

In [19]:
one_arr = np.ones(4)
one_arr

array([1., 1., 1., 1.])

---

3). With Range of elements 

In [20]:
range_arr = np.arange(5)
range_arr

array([0, 1, 2, 3, 4])

---

4). With specific Range of Elements

In [22]:
specific_range_elem = np.arange(3,20)
specific_range_elem

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

---

5). Array with skipping numbers in the range.

In [23]:
skipping_steps_elem = np.arange(4,25,3)
skipping_steps_elem

array([ 4,  7, 10, 13, 16, 19, 22])

---

6). Specfic Data types in array

In [24]:
# With All elements are 1s, same could be created with all elements are zeroes.
specific_DataType_arr1 = np.ones(5, dtype=np.int8)
specific_DataType_arr1

array([1, 1, 1, 1, 1], dtype=int8)

In [26]:
# With range of elements.
specific_DataType_arr2 = np.arange(10, dtype=np.float64)
specific_DataType_arr2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

---

#### 2D Array

In [11]:
arr_2d = np.array([[3,1,9], [5,8,65], [11,9,33]])
arr_2d

array([[ 3,  1,  9],
       [ 5,  8, 65],
       [11,  9, 33]])

In [12]:
# Type of Array
type(arr_2d)

numpy.ndarray

In [13]:
# Length of array
len(arr_2d)

3

In [14]:
# Element from 0th index
arr_2d[0]

array([3, 1, 9])

In [15]:
# All Elements from start to end using indexing
arr_2d[0:]

array([[ 3,  1,  9],
       [ 5,  8, 65],
       [11,  9, 33]])